### ISSUE TITLE
accessType : "offline" doesn't return refreshToken

### ISSUE THREAD

**Issue by peerbolte** [RiptideElements/passport-google-auth#18]
```
new GoogleStrategy(
    {
        clientId: consumerKey,
        clientSecret: consumerSecret,
        accessType: "offline",
        skipUserProfile: true,
        scope: [
            'https://www.googleapis.com/auth/analytics.edit'
        ],
        callbackURL: "/auth/google/callback"
    },
    function (accessToken, refreshToken, profile, done) {
        console.log('refreshToken', refreshToken);
    }
);
```

returns refreshToken as undefined. Am I doing something wrong here?

**Comment by peerbolte** [comment]
I found out this is not an error caused by passport-google-auth. Apparently the refreshtoken is only issued the first time: [stackoverflow](http://stackoverflow.com/questions/8942340/get-refresh-token-google-api). To re-issue it the command prompt has to be forced: approval_prompt=force

**Comment by DavidTPate** [comment]
Interesting, good to know.
